### ISSUE TITLE
Make the UI Good 

### ISSUE THREAD

**Issue by narasimha-1511** [narasimha-1511/travel-planner-app#1]
Currently the UI is very bad and not good

**Comment by cduarte3** [comment]
# Plan
Hello @narasimha-1511 I have made a mockup of a simple UI that can be worked on further in the future once implemented. My plan would be to implement the following by hopefully Friday October 11th 11:59PM EST:

![image](https://github.com/user-attachments/assets/f2a9af99-5b03-4464-b4a9-73507ee92543)

# Request
In implementing this UI overhaul, I would possibly require adding a framework like tailwind or something else. Please let me know if this would be allowed and if you approve of this design?

**Comment by cduarte3** [comment]
# Update
If you would like me to go ahead with the changes, I have started on a separate branch, and the home page now look as follows thus far:

![image](https://github.com/user-attachments/assets/4a8c0754-2d62-49bb-acb8-62773641e637)

**Comment by narasimha-1511** [comment]
Yeah go ahead bro really like it @cduarte3

**Comment by cduarte3** [comment]
Thanks for the update, will be working on the trip page now

**Comment by cduarte3** [comment]
Hello @narasimha-1511 I have made a pull request regarding this issue, please let me know if that request can be assigned to me and if everything is good for merge. Thanks.

**Comment by cduarte3** [comment]
Thank you for the merge @narasimha-1511. Whenever possible, can you please assign me to this PR and add the hacktoberfest label so that it may be counted towards my contributions.
